[package]
name = "network_manager"
version = "0.7.1"
authors = ["Joseph Roberts <joe@resin.io>", "Zahari Petkov <zahari@resin.io>"]

[dependencies]
dbus = "0.5"
futures = "0.1"
futures-cpupool = "0.1"
tokio-timer = "0.1"
bitflags = "0.9"
ascii = "0.8"
log = "0.3"

[dependencies.clippy]
version = "*"
optional = true
