[package]
name = "network_manager"
version = "0.3.1"
authors = ["Joseph Roberts <joe@resin.io>", "Zahari Petkov <zahari@resin.io>"]

[dependencies]
clippy = {version = "*", optional = true}
dbus = "0.5.2"
futures = "0.1.9"
futures-cpupool = "0.1.2"
tokio-timer = "0.1.0"
bitflags = "0.8.0"
ascii = "0.8"
log = "0.3"

[features]
default = []
